language: scala
scala:
   - 2.11.12
   - 2.12.8
   - 2.13.0-M5
jdk:
   - oraclejdk8
   - openjdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
