language: scala
scala:
   - 2.12.10
   - 2.13.1
jdk:
   - openjdk8
   - openjdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
