name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala-version: [2.12.17, 2.13.10]
        java-version: [8, 11, 17]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
      - name: Run tests
        run: sbt ++${{ matrix.scala-version }} clean coverage test coverageReport
      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)
