name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala-version: [2.12.x, 2.13.x]
        java-version: [8, 11, 17, 21]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
      - uses: sbt/setup-sbt@v1
      - name: Run tests
        run: sbt ++${{ matrix.scala-version }} clean coverage test coverageReport
      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)
