name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala-version: [2.12.15, 2.13.8]
        java-version: ["adopt@1.8", 11]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run tests
        run: sbt ++${{ matrix.scala-version }} clean coverage test coverageReport
      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)
